CREATE PUBLICATION same_pub_1;
CREATE PUBLICATION same_pub_2;
CREATE PUBLICATION "same_PUB_3";

CREATE PUBLICATION from_pub_1;

ALTER PUBLICATION same_pub_1 ADD TABLE ONLY customers;

ALTER PUBLICATION same_pub_2 ADD TABLE ONLY customers;
ALTER PUBLICATION same_pub_2 ADD TABLE ONLY products;

ALTER PUBLICATION from_pub_1 ADD TABLE ONLY customers;
